namespace VidiView.Api.DataModel;

/// <summary>
/// The MediaFile contains data for a specific media file (image/video/audio etc)
/// </summary>
[ExcludeFromCodeCoverage]
public record MediaFile
{
    /// <summary>
    /// Date and time this media file was captured/recorded
    /// </summary>
    public DateTimeOffset AcquisitionDate { get; init; }

    /// <summary>
    /// SHA256 checksum of file. 
    /// Byte array sent as a hex string (2 chars per byte)
    /// </summary>
    public string? Checksum { get; init; }

    /// <summary>
    /// The type of content (mime-type) in this media file, i.e. image/jpeg, video/mp4 etc
    /// </summary>
    public string ContentType { get; init; } = string.Empty;

    /// <summary>
    /// Controller where this media file was acquired
    /// </summary>
    public IdAndName? Controller { get; init; }

    /// <summary>
    /// User creating this media file
    /// </summary>
    public IdAndName? CreatedBy { get; init; }

    /// <summary>
    /// If this is set, the media file is deleted
    /// </summary>
    public DateTimeOffset? DeletedDate { get; init; }

    /// <summary>
    /// Id of original media file, from which this media file is derived from
    /// </summary>
    public IdAndName? DerivedFrom { get; init; }

    /// <summary>
    /// Optional description of this media file, given by user
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Id of device where this media file was acquired
    /// </summary>
    public Guid? DeviceId { get; init; }

    /// <summary>
    /// Duration of this media file, if applicable (for video/audio files)
    /// </summary>
    public TimeSpan? Duration { get; init; }

    /// <summary>
    /// Export status of this file
    /// </summary>
    public QueueItemStatus[]? ExportState { get; init; }

    /// <summary>
    /// Specific flags for this media file, i.e. if it is a thumbnail, or a derived image etc
    /// </summary>
    public ImageFlags Flags { get; init; }

    /// <summary>
    /// Media filename, as stored on the server. This is not the original filename, but a unique filename generated by the server
    /// </summary>
    public string Filename { get; init; } = null!;

    /// <summary>
    /// File size in bytes
    /// </summary>
    public long FileSize { get; init; }

    /// <summary>
    /// Height of the image/video in pixels
    /// </summary>
    public int Height { get; init; }

    /// <summary>
    /// The unique media file id
    /// </summary>
    /// <remarks>The name ImageId is legacy and should be changed to Id</remarks>
    public Guid ImageId { get; init; }

    /// <summary>
    /// The index of this media file in the study. This is used to order the media files in a study
    /// </summary>
    public int Index { get; init; }

    /// <summary>
    /// The media type
    /// </summary>
    public MediaType? Type { get; init; }

    /// <summary>
    /// Modality type (DICOM compliant)
    /// </summary>
    public string? Modality { get; init; }

    /// <summary>
    /// Media name, given by user
    /// </summary>
    public string? Name { get; init; }

    /// <summary>
    /// Original filename of a file uploaded to the server
    /// </summary>
    public string? OriginalFilename { get; init; }

    /// <summary>
    /// The origin of this file (Controller / Capture etc..)
    /// </summary>
    public IdAndName Origin { get; init; }

    /// <summary>
    /// Image rotation. If null - check for Exif tags to determine rotation
    /// </summary>
    public int? Rotation { get; init; }

    /// <summary>
    /// Unique series id (DICOM Series Instance UID)
    /// </summary>
    public string SeriesInstanceUid { get; init; } = null!;

    /// <summary>
    /// If several media files are related (captured simultaneously)
    /// they share the same SetId
    /// </summary>
    public Guid? SetId { get; init; }

    /// <summary>
    /// Unique instance id (DICOM SOP Instance UID)
    /// </summary>
    public string SopInstanceUid { get; init; } = null!;

    /// <summary>
    /// Name of the source
    /// </summary>
    public string? Source { get; init; }

    /// <summary>
    /// Detailed information on the source, i.e. hardware identification
    /// </summary>
    public string? SourceDetails { get; init; }

    /// <summary>
    /// Name of the station where this media file was acquired
    /// </summary>
    /// <remarks>Used to populate DICOM Station Name attribute</remarks>
    public string? StationName { get; init; }

    /// <summary>
    /// Media file status
    /// </summary>
    public MediaFileStatus Status { get; init; }

    /// <summary>
    /// Id of the study this media file belongs to
    /// </summary>
    public Guid StudyId { get; init; }

    /// <summary>
    /// Width of the image/video in pixels
    /// </summary>
    public int Width { get; init; }

    /// <summary>
    /// True if this media file is marked as a favourite
    /// </summary>
    public bool IsFavourite { get; init; }

    /// <summary>
    /// Annotations
    /// </summary>
    public Annotation[]? Annotations { get; init; }

    /// <summary>
    /// Anatomic region for this media file
    /// </summary>
    public AnatomicRegion? AnatomicRegion { get; init; }

    /// <summary>
    /// Association with a trackable find
    /// </summary>
    public IdAndName? Trackable { get; init; }

    /// <summary>
    /// Timestamp value that changes with any update
    /// </summary>
    /// <remarks>
    /// This is only changed when actual file metadata is changed, not
    /// annotations, favourite markings etc
    /// </remarks>
    public string Timestamp { get; init; }

    /// <summary>
    /// Position where this media file was created
    /// </summary>
    public double? GeoLongitude { get; init; }

    /// <summary>
    /// Position where this media file was created
    /// </summary>
    public double? GeoLatitude { get; init; }

    /// <summary>
    /// Accuracy of geo location
    /// </summary>
    public double? GeoAccuracy { get; init; }

    /// <summary>
    /// Data specific to the media type. This is a JSON string, 
    /// which can be parsed into a specific object depending on the media type
    /// </summary>
    public string? TypeSpecifics { get; init; }

    /// <summary>
    /// Any HAL Rest links associated with this object
    /// </summary>
    [JsonPropertyName("_links")]
    public LinkCollection? Links { get; init; }

    public override string ToString()
    {
        return $"MediaFile {ImageId} ({ContentType})";
    }
}
