# Copyright (c) 2024 Distributed Medical. All rights reserved.

name: Publish data model

on:
  push:
    branches: [ "main", "release" ]

jobs:

  build-test-and-publish:
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]
        nuget: [latest]

    runs-on: [Windows, self-hosted]
    permissions:
      contents: read
      packages: write

    env:
      SOLUTION: VidiView.DataModel.sln

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore ${{env.SOLUTION}}
    - name: Build
      run: dotnet build ${{env.SOLUTION}} --arch ${{ matrix.platform }} --configuration ${{ matrix.configuration }} --no-restore
    - name: Test
      run: dotnet test ${{env.SOLUTION}} --no-build --verbosity normal
